### ISSUE TITLE
About BaseModel.load

### ISSUE THREAD

**Issue by ulamaca** [MrGemy95/Tensorflow-Project-Template#11]
To load the model properly, I think we need: 
    def load(self, sess):
        latest_checkpoint = tf.train.latest_checkpoint(self.config.checkpoint_dir)
        ...

Instead of the original
        latest_checkpoint = tf.train.latest_checkpoint(os.path.join(self.config.checkpoint_dir, self.config.exp_name))

**Comment by mgsalem** [comment]
yes, you're right
i modified it.
Thank you.
