### ISSUE TITLE
from bunch import Bunch

### ISSUE THREAD

**Issue by facereg** [MrGemy95/Tensorflow-Project-Template#13]
Hi Mr Gemy95,
Thanks for your tensorflow-template. While, in the sample "utils/config.py" , that indicated as "**from bunch import Bunch**", the question is where is bunch and what's the function of bunch? Is there another folder named "bunch"?
Waiting for you reply. My email address is `littleforce@163.com`, you may send to me directly.

**Comment by mgsalem** [comment]
I use Bunch to convert the config dictionary into a namespace. I'll update it to "easy dict" lib soon.
but the point is i want to access the config key by "dot" operation.
