### ISSUE TITLE
About the `init_saver` of base_model?

### ISSUE THREAD

**Issue by imhuay** [MrGemy95/Tensorflow-Project-Template#17]
Why don't direct use the implement in the annotation?
```
    def init_saver(self):
        # just copy the following line in your child class
        # self.saver = tf.train.Saver(max_to_keep=self.config.max_to_keep)
        raise NotImplementedError
```

**Comment by mgsalem** [comment]
as "tf.train.Saver" takes the current tensorflow variables and save them, so calling this before building the model will save nothing and will lead to a serious bug, so i preferred to force this function to be implemented in the child class.
