### ISSUE TITLE
What is the point "cur_epoch_tensor" and "global_step_tensor"?

### ISSUE THREAD

**Issue by WrathOfGrapes** [MrGemy95/Tensorflow-Project-Template#27]
Why keeping track  of epoch and step counts is implemented with tensorflow Variables, instead of plain python variables?

It seems that it is not very efficient to store them like that, considering that they will probably be placed on GPU with other tf variables.

Is there any use case I'm missing?

**Comment by mgsalem** [comment]
To keep track of the training process in case of stopping the experiments and running them again.
