### ISSUE TITLE
validation cycles

### ISSUE THREAD

**Issue by ferreirafabio** [MrGemy95/Tensorflow-Project-Template#33]
Thank you for providing this beautiful template. 

I was wondering where I'd ideally put validation cycles, say every 1000 iterations, in this structure. Any recommendations?

**Comment by moemen95** [comment]
Hello,

Yes you can,
https://github.com/MrGemy95/Tensorflow-Project-Template/blob/master/base/base_train.py

you can make afunction called validate_epoch ok?! 
Then call it in function train after self.train_epoch()
