### ISSUE TITLE
why Trainers?

### ISSUE THREAD

**Issue by mouradyahia** [MrGemy95/Tensorflow-Project-Template#34]
My question is not about the implementation details. It is more of a strategic question.
I want to know the advantage of using a trainer class instead of incorporating the training in the model class as a method.
Thank you for this very clean template!

**Comment by mgsalem** [comment]
It's for modularity. usually you have more than one model to compare in your project, so there's no meaning for writing the training part more than once, so you just have one trainer and pass any model to it.
