### ISSUE TITLE
I think might some problem here

### ISSUE THREAD

**Issue by HannH** [MrGemy95/Tensorflow-Project-Template#5]
https://github.com/MrGemy95/Tensorflow-Project-Template/blob/e873ec8c97dea7fee2c70fc7f5ace362a9d29339/models/example_model.py#L23
I think it maybe not good idea writing optimizer there. Programer need to shrink the model size when release a well trained model. Sometimes we may want to save variables except optimizer like this:
```
net = ExampleModel.build_model(...)#only net defines inside
saver = tf.train.Saver()
with tf.Session() as sess:
    saver.restore(sess, model_path)
    ...
    do something to resave model for shrink size
    ...
``` 
It will be trouble in such situation when you put the model defines and optmizer together

**Comment by MrGemy95** [comment]
> Programer need to shrink the model size when release a well trained model. 
This's right, but separating the train_step form the model isn't the only solution, that's  why i left "init_saver" not implemented so you can easily give it the list of variables you want to save. in this case simply exclude the optimizer variables from the list you give to the tensorflow saver.

**Comment by mgsalem** [comment]
>Programer need to shrink the model size when release a well trained model.

This's right, but separating the train_step form the model isn't the only solution, that's  why i left "init_saver" not implemented so you can easily give it the list of variables you want to save. in this case simply exclude the optimizer variables from the list you give to the tensorflow saver.
